services:
  smtp_proxy_server:
    build:
      context: .
      dockerfile: dockerfile
    container_name: "smtp_proxy_server"
    ports:
      - "8025:8025"
      - "11143:11143"
    environment:
      - proxy_url=https://mail-api.example.com
      - port=8025
      - imap_port=11143
