name = "email-transfer-station-pages"
pages_build_output_dir = "../frontend/dist"
compatibility_date = "2024-05-13"

[[services]]
binding = "BACKEND"
service = "email-transfer-station-api"
environment = "production"
